ssh_public_key = "<your public key>"
latitudesh_token = "<TOKEN>"
region = "ASH"
plan = "s3.large.x86"
plan_name = "Solana Validator"
plan_description = "Solana Validator"
plan_environment = "Development"
